export const adminStyles = {
  page: "min-h-screen bg-slate-50 pt-20 pb-12",
  container: "section-container max-w-6xl",
  header: "flex items-center justify-between mb-8",
  title: "text-2xl font-bold text-slate-900",
  card: "glass-card rounded-2xl p-6 mb-4 flex items-center justify-between gap-4 bg-white",
  cardTitle: "text-lg font-semibold text-slate-900",
  cardMeta: "text-slate-500 text-sm mt-1",
  published: "bg-teal-50 text-teal-700 border border-teal-200 px-2 py-1 rounded-full text-xs",
  draft: "bg-orange-50 text-orange-700 border border-orange-200 px-2 py-1 rounded-full text-xs",
  form: "glass-card rounded-2xl p-8 space-y-6 max-w-3xl mx-auto bg-white",
  field: "space-y-2",
  label: "text-sm text-slate-600",
  input: "w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 focus:outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100",
  textarea: "min-h-[120px] resize-y",
  row: "flex items-center gap-4",
  checkbox: "flex items-center gap-2 text-slate-600 text-sm",
  previews: "flex flex-wrap gap-3 mt-3",
  preview: "w-20 h-20 rounded-lg object-cover border border-slate-200",
  actions: "flex items-center gap-2 justify-end pt-4",
  error: "text-orange-600 text-sm",
};
