export const adminStyles = {
  page: "min-h-screen bg-[#050816] pt-20 pb-12",
  container: "section-container max-w-6xl",
  header: "flex items-center justify-between mb-8",
  title: "text-2xl font-bold text-white",
  card: "glass-card rounded-2xl p-6 mb-4 flex items-center justify-between gap-4",
  cardTitle: "text-lg font-semibold text-white",
  cardMeta: "text-white/40 text-sm mt-1",
  badge: "px--2 py-1 rounded-full text-xs",
  published: "bg-green-500/10 text-green-400 border border-green-500/20 px-2 py-1 rounded-full text-xs",
  draft: "bg-yellow-500/10 text-yellow-400 border border-yellow-500/20 px-2 py-1 rounded-full text-xs",
  form: "glass-card rounded-2xl p-8 space-y-6 max-w-3xl mx-auto",
  field: "space-y-2",
  label: "text-sm text-white/60",
  input: "w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white focus:outline-none focus:border-cyan-500/50",
  textarea: "min-h-[120px] resize-y",
  row: "flex items-center gap-4",
  checkbox: "flex items-center gap-2 text-white/70 text-sm",
  previews: "flex flex-wrap gap-3 mt-3",
  preview: "w-20 h-20 rounded-lg object-cover border border-white/10",
  actions: "flex items-center gap-2 justify-end pt-4",
  loginWrap: "min-h-screen flex items-center justify-center bg-[#050816]",
  loginForm: "glass-card rounded-2xl p-8 w-full max-w-md space-y-6 glow-border",
  loginTitle: "text-2xl font-bold text-white text-center mb-2",
  error: "text-red-400 text-sm text-center",
};
