export const navbarStyles = {
  nav: "fixed top-0 left-0 right-0 z-50 transition-all duration-500 overflow-visible",
  scrolled: "bg-white/90 backdrop-blur-xl border-b border-slate-200 shadow-sm shadow-teal-500/5",
  transparent: "bg-transparent",
  inner: "section-container flex items-center justify-between h-16 md:h-20 gap-4",
  logo: "group flex items-center gap-3 shrink-0 transition-opacity hover:opacity-90",
  logoAvatarWrap:
    "relative shrink-0 w-9 h-9 md:w-10 md:h-10 rounded-full overflow-hidden shadow-[0_2px_10px_rgba(15,23,42,0.18)] transition-transform duration-300 group-hover:scale-105",
  logoAvatarWrapLight: "ring-1 ring-white/50",
  logoAvatarWrapDark: "ring-1 ring-slate-200",
  logoAvatar: "w-full h-full object-cover object-[center_22%]",
  logoText: "text-lg md:text-xl font-bold font-[family-name:var(--font-display)] tracking-tight",
  logoTextLight: "text-white drop-shadow-[0_1px_3px_rgba(0,0,0,0.6)]",
  logoTextDark: "text-slate-900",
  logoBrand: "inline-flex items-baseline [unicode-bidi:isolate]",
  logoAccentLight: "text-teal-300",
  logoAccentDark: "text-teal-600",
  links: "hidden lg:flex items-center gap-1",
  navIconActive: "!bg-teal-100 !border-teal-400 !text-teal-700 shadow-sm shadow-teal-100",
  actions: "flex items-center gap-2 shrink-0",
  langToggle: "flex items-center rounded-xl border border-slate-200 overflow-hidden bg-white shadow-sm",
  langBtn: "px-3 py-1.5 text-xs font-semibold transition-colors",
  langBtnActive: "bg-teal-600 text-white",
  langBtnInactive: "text-slate-500 hover:bg-slate-50",
  mobileBtn: "lg:hidden",
  mobileMenu: "fixed inset-0 z-50 bg-white/95 backdrop-blur-xl flex flex-col items-center justify-center gap-8 lg:hidden",
  mobileNavGrid: "flex flex-wrap items-center justify-center gap-4 max-w-sm",
};
